data:
  paths:
    base: "data"
    hf: "${data.paths.base}/hateful_memes_hf"
    labels_file: "${data.paths.base}/labels.jsonl"
    calibration_file: "${data.paths.base}/labels_calibration.jsonl"
    reannotation_file: "${data.paths.base}/labels_reannotation.jsonl"
  final_dataset: "nils-herrmann/hateful_memes_multilabel"
out:
  path: "out"
  runs: "out/runs"
  results: "out/results"
  logs: "logs"

gpt:
  model: "gpt-5.1-2025-11-13"
  concurrent_requests: 105

training:
  # Pre-trained model
  model: "unsloth/llava-v1.6-mistral-7b-hf-bnb-4bit" #unsloth/llava-v1.6-mistral-7b-hf-bnb-4bit unsloth/Qwen2.5-VL-7B-Instruct-unsloth-bnb-4bit
  load_in_4bit: true
  use_gradient_checkpointing: "unsloth"
  max_seq_length: 2048

  # Input data
  img_size: [512, 512]
  img_color_padding: [255, 255, 255]

  # LoRA parameters
  lora_r: 64
  lora_alpha: 128
  lora_dropout: 0
  
  # Training configuration
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  warmup_steps: 40
  num_train_epochs: 2
  learning_rate: 2e-4
  logging_steps: 5
  optim: "adamw_8bit"
  weight_decay: 0.1
  lr_scheduler_type: "cosine"
  seed: 3407
  
  # Vision finetuning specific
  remove_unused_columns: false
  dataset_text_field: ""
  dataset_num_proc: 4
  
  # Save strategy
  save_strategy: "no"
  save_total_limit: null
  
  # Reporting
  report_to: "wandb"

# Weights & Biases configuration
wandb:
  project: "beyond_hate"

# Results for bias analysis
results_ids:
  coarse:
    - model: "unsloth/Qwen2.5-VL-7B-Instruct-unsloth-bnb-4bit"
      run_id: "wdni3pka"
    - model: "unsloth/llava-v1.6-mistral-7b-hf-bnb-4bit"
      run_id: "32sksqu5"
  fine:
    - model: "unsloth/llava-v1.6-mistral-7b-hf-bnb-4bit"
      run_id: "nki2rqks"
    - model: "unsloth/Qwen2.5-VL-7B-Instruct-unsloth-bnb-4bit"
      run_id: "8rhjtcdu"
  joint:
    - model: "unsloth/llava-v1.6-mistral-7b-hf-bnb-4bit"
      run_id: "qj2shp9p"
    - model: "unsloth/Qwen2.5-VL-7B-Instruct-unsloth-bnb-4bit"
      run_id: "t1c0jd4t"
